package com.rabbit.common.enums.rabbitmq;

import java.util.List;

import com.google.common.collect.ImmutableList;

public enum RabbitReceivedDataType {
/*********************************************  product   *******************************************************************/
	RABBIT_PRODUCT_PUSH_TYPE("RABBIT_PRODUCT_PUSH",ImmutableList.of("node","user")), // 结构：key:key  list:为参数列表对应key的集合
	RABBIT_PRODUCT_PUSHMUTIL_TYPE("RABBIT_PRODUCT_PUSHMUTIL_TYPE",null),
	RABBIT_PRODUCT_ADD_COST_TYPE("RABBIT_PRODUCT_ADD_COST_TYPE",null),
	RABBIT_PRODUCT_UPDATE_PRICE_TYPE("RABBIT_PRODUCT_UPDATE_PRICE_TYPE",null),
	RABBIT_PRODUCT_UPDATE_STATUS_TYPE("RABBIT_PRODUCT_UPDATE_STATUS_TYPE",null),
	RABBIT_PRODUCT_ADD_URL_TYPE("RABBIT_PRODUCT_ADD_URL_TYPE",null),
	RABBIT_PRODUCT_ADD_SELLING_POINT_TYPE("RABBIT_PRODUCT_ADD_SELLING_POINT_TYPE",null),
	RABBIT_PRODUCT_ADD_PRODUCT_IMAGE_TYPE("RABBIT_PRODUCT_ADD_PRODUCT_IMAGE_TYPE",null),
	RABBIT_PRODUCT_ADD_LABEL_TYPE("RABBIT_PRODUCT_ADD_LABEL_TYPE",null),
	RABBIT_PRODUCT_DELETE_LABEL_TYPE("RABBIT_PRODUCT_DELETE_LABEL_TYPE",null),
	RABBIT_PRODUCT_UPDAET_LABEL_TYPE("RABBIT_PRODUCT_UPDAET_LABEL_TYPE",null),
	RABBIT_PRODUCT_ADD_TRANSLATION_TYPE("RABBIT_PRODUCT_ADD_TRANSLATION_TYPE",null),
	RABBIT_PRODUCT_UPDAET_TRANSLATION_TYPE("RABBIT_PRODUCT_UPDAET_TRANSLATION_TYPE",null),
	RABBIT_PRODUCT_UPDAET_STORAGE_TYPE("RABBIT_PRODUCT_UPDAET_STORAGE_TYPE",null),
	RABBIT_PRODUCT_UPDAET_QTY_TYPE("RABBIT_PRODUCT_UPDAET_QTY_TYPE",null),
	RABBIT_PRODUCT_UPDAET_FREIGHT_TYPE("RABBIT_PRODUCT_UPDAET_FREIGHT_TYPE",null),
	RABBIT_PRODUCT_SALE_PRICE_TYPE("RABBIT_PRODUCT_SALE_PRICE_TYPE",null),
	RABBIT_PRODUCT_DELETE_CURRENT_SALEPRICE_TYPE("RABBIT_PRODUCT_DELETE_CURRENT_SALEPRICE_TYPE",null),
	RABBIT_PRODUCT_DELETE_SELLING_POING_TYPE("RABBIT_PRODUCT_DELETE_SELLING_POING_TYPE",ImmutableList.of("listingid","lang")),
	RABBIT_PRODUCT_DELETE_SALE_PRICE_TYPE("RABBIT_PRODUCT_DELETE_SALE_PRICE_TYPE",null),
	RABBIT_PRODUCT_COTY_TYPE("RABBIT_PRODUCT_COTY_TYPE",null),
	RABBIT_PRODUCT_DELETE_IMAGE_TYPE("RABBIT_PRODUCT_DELETE_IMAGE_TYPE",ImmutableList.of("listingid","websiteid")),
	RABBIT_PRODUCT_ADD_CATEGORY_TYPE("RABBIT_PRODUCT_ADD_CATEGORY_TYPE",null),
	RABBIT_PRODUCT_PUSH_PRODUCT_CATEGORY_TYPE("RABBIT_PRODUCT_PUSH_PRODUCT_CATEGORY_TYPE",null),
	
	/*********************************************  ThirdPlatformData   *******************************************************************/	
	RABBIT_THIREDPLATFORMDATE_PUSH_TYPE("RABBIT_THIREDPLATFORMDATE_PUSH_TYPE",null),
	/*********************************************  KEYWORD   *******************************************************************/	
	RABBIT_KEYWORD_PUSH_TYPE("RABBIT_KEYWORD_PUSH_TYPE",null),
	/*********************************************  ATTRIBUTE   *******************************************************************/	
	RABBIT_ATTRIBUTE_PUSH_TYPE("RABBIT_ATTRIBUTE_PUSH_TYPE",null),
	RABBIT_ATTRIBUTE_ADD_PRODUCT_MULTI_ATTRIBUTE_TYPE("RABBIT_ATTRIBUTE_ADD_PRODUCT_MULTI_ATTRIBUTE_TYPE",null),
	RABBIT_ATTRIBUTE_DELETE_MULTI_PRODUCT_ATTRIBUTE_TYPE("RABBIT_ATTRIBUTE_DELETE_MULTI_PRODUCT_ATTRIBUTE_TYPE",ImmutableList.of("parentSku","key","languageId","websiteId")),
	RABBIT_ATTRIBUTE_DELETE_PRODUCT_ATTRIBUTE_TYPE("RABBIT_ATTRIBUTE_DELETE_PRODUCT_ATTRIBUTE_TYPE",ImmutableList.of("listingid","key","languageId")),
	RABBIT_ATTRIBUTE_ADD_PRODUCT_ATTRIBUTE_TYPE("RABBIT_ATTRIBUTE_ADD_PRODUCT_ATTRIBUTE_TYPE",null),
	
	/*********************************************  CATEGORY  *******************************************************************/	
	RABBIT_CATEGORY_PUSH_TYPE("RABBIT_CATEGORY_PUSH_TYPE",null),
	RABBIT_CATEGORY_SAVE_UPDATE_CATEGORY_BASE_TYPE("RABBIT_CATEGORY_SAVE_UPDATE_CATEGORY_BASE_TYPE",null),
	RABBIT_CATEGORY_PLATFORM_PUSH_TYPE("RABBIT_CATEGORY_PLATFORM_PUSH_TYPE",null),
	RABBIT_CATEGORY_SAVE_UPDATE_PLATFORM_CATEGORY_TYPE("RABBIT_CATEGORY_SAVE_UPDATE_PLATFORM_CATEGORY_TYPE",null),
	RABBIT_CATEGORY_GET_TYPE("RABBIT_CATEGORY_GET_TYPE",ImmutableList.of("websiteid","languageid")),
	RABBIT_CATEGORY_SAVE_CATEGORY_ATTRIBUTES_TYPE("RABBIT_CATEGORY_SAVE_CATEGORY_ATTRIBUTES_TYPE",null);
	
	
	private String key;
	private List<String> params; 

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public List<String> getParams() {
		return params;
	}

	public void setParams(List<String> params) {
		this.params = params;
	}

	private RabbitReceivedDataType(String key,List<String> params ) {
		this.key = key;
		this.params=params;
	}
}